DROP TABLE IF EXISTS user;

CREATE TABLE user(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  lastName VARCHAR(250) NOT NULL,
  firstName VARCHAR(250) NOT NULL,
  companyName VARCHAR(250) DEFAULT NULL
);
COMMIT;